a = input("Digite algo: ")
print("O tipo primitivo desse valor é ", type(a))
print("Só tem espaços?", a.isspace())
print("É um número? ", a.isnumeric())
print("É alfabético? ", a.isalpha())
print("É alfanumérico? ", a.isalnum())
print("Está em minúsculas? ", a.islower())
print("Está em maiúsculas? ", a.istitle())
print("Está capitalizada? ", a.isupper())